{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"UNIT_OCCUPANCY_DAILY\",\"PROPERTY_AGE_RECEIVABLES_MONTHLY\",\"LEASE_PROGRESSION_DAILY\",\"TRANSACTION_CHARGES_COLLECTIONS_MONTHLY\",\"LEASE_EXPIRATION_DAILY\",\"UNIT_SPACE_RENT_GROWTH_DAILY\",\"LEAD_SOURCE_DAILY\",\"MAINTENANCE_REQUEST_DAILY\",\"TimeSeries\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "unit_occupancy_daily.month_evnt": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Month Evnt"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Month": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "unit_occupancy_daily.quarter_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Quarter Year"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "QtrYear": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "unit_occupancy_daily.weekday_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Weekday 1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Weekday": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "UNIT_OCCUPANCY_DAILY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fface54f-9256-40da-8423-6b9377db46a6",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "725b9bb7-c8c5-4e39-a0d0-8e4184676075",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c99ab5b7-5fed-4555-a134-883faa245376",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b472742-5074-4e4a-b756-f9ab04684986",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96da28b8-fb19-424c-92e6-cc7c50c004da",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c4e2628-dbae-4a7f-af01-df3f8d398646",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3b9ea98-eee0-4884-88da-4c6c18bc3b56",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "083740af-ccba-4c9c-a963-97f0c62a46ad",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cbac884-02dc-4210-8033-095e12895b2d",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e627cf50-5c1f-4f0a-97c2-4eb51f4fcc45",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3efca71-dede-4b89-a5d4-c50c5df87abb",
            "sourceColumn": "Unit Type",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3b92ec6-dab4-446b-a251-7cfd9348f323",
            "sourceColumn": "Unit Number",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31cea10d-117f-41a2-8c46-661473782e9f",
            "sourceColumn": "Unit Status",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e7f44d0-a6ff-41ff-aba8-12d5fc4c71a6",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "309d40e2-5411-467f-bada-48812a90855b",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Model Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9df64f21-a360-43b2-9750-5d564b2b74d1",
            "sourceColumn": "Model Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Down Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a209667-b5db-4968-bae2-a4fdbcb8cb16",
            "sourceColumn": "Down Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52e157a8-fdfa-4965-9d90-a18aa9ff3004",
            "sourceColumn": "Rentable Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Occupied Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3b5e693-83f9-4b00-a971-1f8929e46388",
            "sourceColumn": "Occupied Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Vacant Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20db4e1d-ac98-4cb0-b47a-e4e8111a57c8",
            "sourceColumn": "Rentable Vacant Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Leased Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b863ea5f-48a4-4d05-8e00-2b26d5419a16",
            "sourceColumn": "Rentable Leased Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "806c4f52-de4d-464c-aac0-33dc4459b8e2",
            "sourceColumn": "Rentable Trend Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Exposed Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e828637-11eb-45d4-a15a-27f7f1715f0c",
            "sourceColumn": "Rentable Exposed Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend 30 Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0c87bff-e548-4b0a-b272-d7d4164d993e",
            "sourceColumn": "Rentable Trend 30 Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend 60 Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ef42efc-6fc2-4dd5-9f64-bf26d44da8b2",
            "sourceColumn": "Rentable Trend 60 Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Unrented Not Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dc642b20-595c-4551-8902-c1658267fee2",
            "sourceColumn": "Vacant Unrented Not Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Unrented Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d79e1eb1-bdb1-428b-a36c-b231d2f8e15b",
            "sourceColumn": "Vacant Unrented Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Rented Not Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65807fe5-a688-4212-8b65-011fce1840ac",
            "sourceColumn": "Vacant Rented Not Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Rented Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f88c1ed-a5b0-4952-a0fa-6df484823744",
            "sourceColumn": "Vacant Rented Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ce81d49-93f1-4e8f-a139-8234683418a5",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98d00e06-9950-4928-b18f-5dd8a5403503",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a1d6258-e140-43dc-b7b9-29d69de9eb51",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f970ed1-303d-405b-b095-e02f58ee305a",
            "sourceColumn": "Future Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ad36b67-874d-4a4c-bedc-1de0ff922dd4",
            "sourceColumn": "Future Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32eb216a-ae13-4642-883e-6682e2bee23e",
            "sourceColumn": "Future Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1e95f4f-c238-4b3a-80d1-abc19db4df4c",
            "sourceColumn": "Prior Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "952fde0d-0383-42fd-9081-34e7098e556a",
            "sourceColumn": "Prior Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9efdbad-ec26-43db-a538-06d61f1d7845",
            "sourceColumn": "Prior Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aee4222-02d4-4fe9-84b3-c2495a46dbbb",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Future Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "462f25f2-0a40-4bb9-a410-fdbf8ddd2e48",
            "sourceColumn": "Future Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2fd82a6-15df-4797-ae26-f073941890a0",
            "sourceColumn": "Prior Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Future Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9934293b-6d5f-4c45-8aec-d155c3a41615",
            "sourceColumn": "Future Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ea7af308-0b4e-4f3c-848d-6e15450745b8",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8951790c-69e8-4f00-a7f1-bb72eb54d6d2",
            "sourceColumn": "Prior Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "45b363f4-12cb-43b5-9a7e-25df0ea8493d",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ee37eb79-d284-4bf5-9260-b789432d8ab7",
            "sourceColumn": "Prior Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Days Vacant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2a4f32c-0d1b-4f95-bf61-83f307c88810",
            "sourceColumn": "Days Vacant",
            "summarizeBy": "sum"
          },
          {
            "name": "Notice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "645afc94-60fc-4e12-a74d-2fea51568662",
            "sourceColumn": "Notice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Notice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f26f39b4-45b4-4a97-b15a-0baa2ded90cf",
            "sourceColumn": "Prior Notice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Leased Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d47da580-7ead-4566-858b-e7d399b0728a",
            "sourceColumn": "Leased Date",
            "summarizeBy": "none"
          },
          {
            "name": "Vacant Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "83e23965-8eb5-41d4-8466-4785200c90ba",
            "sourceColumn": "Vacant Date",
            "summarizeBy": "none"
          },
          {
            "name": "Occupied Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "fedc3c3d-b8de-45ce-a4eb-422a1408c0bc",
            "sourceColumn": "Occupied Date",
            "summarizeBy": "none"
          },
          {
            "name": "Square Feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0bd00652-f685-4055-8e37-d5a9d35e84a8",
            "sourceColumn": "Square Feet",
            "summarizeBy": "sum"
          },
          {
            "name": "Bedroom Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2c9a607-1730-4357-9f1d-0da16a4e6817",
            "sourceColumn": "Bedroom Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Bathroom Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "42659876-3aff-4ead-8102-ef12a65ea17d",
            "sourceColumn": "Bathroom Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Make Ready Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f2b2eefa-eb29-45a6-95a9-1f3fa2f61c8f",
            "sourceColumn": "Make Ready Date",
            "summarizeBy": "none"
          },
          {
            "name": "Available On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f0469a36-7f39-4204-aab4-a311ec38dbdc",
            "sourceColumn": "Available On",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e116ab0-f44e-4516-b1de-04cca5e4aebd",
            "sourceColumn": "Budgeted Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Current MTM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a1c7bed4-4a37-4a1c-b138-ff39917e7628",
            "sourceColumn": "Current MTM",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d97e3070-1294-4d7e-91ea-370de62ea40c",
            "sourceColumn": "Vacant Units",
            "summarizeBy": "sum"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "382001ec-2c4d-4c8d-95eb-955ecc71f847",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bb5307a3-988d-4732-95bf-d4b69b9d0505",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d9293ff-0be9-49c2-8b32-be13f103776c",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Floor Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29d60680-eed6-4a04-b839-9935957d5a4a",
            "sourceColumn": "Floor Plan",
            "summarizeBy": "none"
          },
          {
            "name": "Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f1778e8-5af0-4f1a-b8f0-3c05671fea0a",
            "sourceColumn": "Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "440a1ccc-62d8-4cca-8830-7d42611a7fd4",
            "sourceColumn": "Scheduled Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Charges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "415dd021-f4bc-464e-99e0-85bde93e335e",
            "sourceColumn": "Scheduled Charges",
            "summarizeBy": "sum"
          },
          {
            "name": "Market Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef3dd850-b4eb-4ddc-9757-565e70d104a0",
            "sourceColumn": "Market Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Days On Market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cea17276-30ea-4c79-954b-b7d4154f79e4",
            "sourceColumn": "Days On Market",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c93ecd1c-8f5e-45f7-b80d-1f6e135785ba",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9ceaef4a-9fc4-43dc-b44a-4b6f841df994",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-1,\"Current\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-8,\"-7\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-15,\"-14\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-22,\"-21\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-29,\"-28\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-31,\"-30\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-61,\"-60\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+6,\"+7\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+13,\"+14\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+20,\"+21\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+27,\"+28\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+31,\"+30\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+61,\"+60\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+91,\"+90\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+121,\"+120\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4cda86b3-a1fc-4248-b9c1-6fff805de009",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "YEAR(UNIT_OCCUPANCY_DAILY[Event Date])&\"  Q\"&QUARTER(UNIT_OCCUPANCY_DAILY[Event Date])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "acef4278-57e2-4ec2-989d-3e14e2d8b26e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Evnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(UNIT_OCCUPANCY_DAILY[Event Date],\"MMM\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bdc2f40b-cc11-400a-88b4-b260cfd9976f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthYearnum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(",
              "    UNIT_OCCUPANCY_DAILY[Event Date],",
              "    \"YYYYMM\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "81055a53-eb7a-4c2f-9924-24ffea40056e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "6999991a-40fe-4401-8aad-0f8071b423cd",
        "partitions": [
          {
            "name": "UNIT_OCCUPANCY_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"Compute_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    UNIT_OCCUPANCY_DAILY_View = DASHBOARD_Schema{[Name=\"UNIT_OCCUPANCY_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    UNIT_OCCUPANCY_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MeasureExecutiveSummary",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d2d94abeca3645c0ade22dccca6c74b4"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "65a78f37-f24b-4d62-a22b-0808cc5bcf72",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3178b282-5cf3-455a-bd5f-c448568f2b62",
        "measures": [
          {
            "name": "Occupancy %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Occupied Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f56caa7e-67ca-4837-b672-d58da31dc15a"
          },
          {
            "name": "Leased %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Leased Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82932ffc-9d8f-418e-86eb-99518aafc7ce"
          },
          {
            "name": "Exposed %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Exposed Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "89e96319-6d09-4726-bc0b-e05027c7af96"
          },
          {
            "name": "Net Performed Move-Ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(LEASE_PROGRESSION_DAILY[Performed Move-in Count])-sum(LEASE_PROGRESSION_DAILY[Performed Move-out Count])"
            ],
            "lineageTag": "3b3a9b68-6705-463c-8447-812697706767"
          },
          {
            "name": "Current Month Net Move Ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(LEASE_PROGRESSION_DAILY[Performed Move-in Count]),",
              "    LEASE_PROGRESSION_DAILY[Event Date]>=TODAY())",
              "-",
              "CALCULATE(",
              "    SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-out Count]),",
              "    LEASE_PROGRESSION_DAILY[Event Date]>=TODAY())",
              ""
            ],
            "lineageTag": "10dc7c67-9e60-4a8f-9265-b3e59666fb8e"
          },
          {
            "name": "Net Scheduled Move-ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-in Count])-SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-out Count])"
            ],
            "lineageTag": "93d4225e-9270-4eac-af92-ab0b0bde1d44"
          },
          {
            "name": "Trend %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Trend Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f54c80ee-6a27-4975-a872-2219e58f629f"
          },
          {
            "name": "60th Day",
            "expression": [
              "",
              "CALCULATE(",
              "    [Occupancy %],",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-60",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d3f12397-4687-4463-b3f2-3c794ca38e81"
          },
          {
            "name": "30th Day",
            "expression": [
              "",
              "CALCULATE(",
              "    [Occupancy %],",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-30",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e4170bb0-3dfc-483a-adf0-a617bc3077ce"
          },
          {
            "name": "Weekday",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-1,\"Current\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-8,\"-7\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-15,\"-14\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-22,\"-21\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-29,\"-28\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-31,\"-30\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-61,\"-60\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+6,\"+7\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+13,\"+14\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+20,\"+21\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+27,\"+28\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+31,\"+30\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+61,\"+60\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+91,\"+90\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+121,\"+120\"",
              "    )"
            ],
            "lineageTag": "b1675ba6-1ff3-4fac-8cec-6cc2c02ce02d"
          },
          {
            "name": "WeekdayColor",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Weekday 1]),",
              "    \"Current\",\"#9D6E9C\",",
              "    \"-7\",\"#C6ABC6\",\"-14\",\"#C6ABC6\",\"-21\",\"#C6ABC6\",\"-28\",\"#C6ABC6\",\"-30\",\"#C6ABC6\", \"-60\",\"#C6ABC6\",",
              "    \"+7\",\"#E0E0E0\",\"+14\",\"#E0E0E0\",\"+21\",\"#E0E0E0\",\"+28\",\"#E0E0E0\",\"+30\",\"#E0E0E0\",\"+60\",\"#E0E0E0\",\"+120\",\"#E0E0E0\",\"+90\",\"#E0E0E0\")",
              ""
            ],
            "lineageTag": "bb25125a-390a-4647-b7a2-ff0da77d46d8"
          },
          {
            "name": "Avg Occupancy",
            "expression": [
              "",
              "DIVIDE(",
              "    AVERAGE(UNIT_OCCUPANCY_DAILY[Occupied Unit Count]),",
              "    AVERAGE(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "33ea18d0-9503-4ae2-b74a-71e299020f45"
          },
          {
            "name": "% Collected",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts])+SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts]),",
              "    SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges]),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cb683e03-1bb4-4ee3-b8f7-ee21996ab25e"
          },
          {
            "name": "Uncollected",
            "expression": [
              "",
              "SUMX(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY,",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges]-((TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts]+TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts])+TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Credit Concessions]))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e65741aa-27e5-4ba9-82ff-aa4cbc5df4bf"
          },
          {
            "name": "Renewal Ratio",
            "expression": [
              "",
              "IF(",
              "    SUM(LEASE_EXPIRATION_DAILY[Expiration Count]) = 0,",
              "    0,",
              "    DIVIDE(",
              "        SUM(LEASE_EXPIRATION_DAILY[Renewal Count]),",
              "        SUM(LEASE_EXPIRATION_DAILY[Expiration Count])",
              "    )",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "07a7f0b1-fa5e-417a-981d-d1f989de2d0c"
          },
          {
            "name": "% Change",
            "expression": [
              "",
              "IF(",
              "    AVERAGE('UNIT_SPACE_RENT_GROWTH_DAILY'[Prior Effective Rent]) = 0,",
              "    0,",
              "    DIVIDE(",
              "        AVERAGE('UNIT_SPACE_RENT_GROWTH_DAILY'[Effective Rent]) - AVERAGE('UNIT_SPACE_RENT_GROWTH_DAILY'[Prior Effective Rent]),",
              "        AVERAGE('UNIT_SPACE_RENT_GROWTH_DAILY'[Prior Effective Rent])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9af98b3c-ed0d-4dd3-8363-273389f22352"
          },
          {
            "name": "%Change - Renewal",
            "expression": [
              "",
              "var avgprioreffectiverenewal = ",
              "AVERAGEX(",
              "    FILTER(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY,",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] = \"Renewal\"),",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "var avgeffectiverenewal =",
              "AVERAGEX(",
              "    FILTER(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY,",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type]= \"Renewal\"),",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent]",
              ")",
              "var effectivesub = avgprioreffectiverenewal - avgeffectiverenewal",
              "",
              "return",
              "IF(",
              "    avgprioreffectiverenewal = 0,",
              "    0,",
              "    DIVIDE(",
              "    effectivesub,",
              "    avgeffectiverenewal",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "303d188e-a754-46e7-b74f-b4a9af54cefd"
          },
          {
            "name": "%Change-Application",
            "expression": [
              "",
              "var avgprioreffectiverent = ",
              "AVERAGEX(",
              "    FILTER(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY,",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] IN {\"Application\",\"Transfer\"}),",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "var avgeffectiverent =",
              "AVERAGEX(",
              "    FILTER(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY,",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] IN {\"Application\",\"Transfer\"}),",
              "         UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent]",
              ")",
              "var effectivesub = avgprioreffectiverent - avgeffectiverent",
              "",
              "return",
              "IF(",
              "    avgprioreffectiverent = 0,",
              "    0,",
              "    DIVIDE(",
              "    effectivesub,",
              "    avgprioreffectiverent",
              ")",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "91b888de-e309-4ba9-88f4-046dd79be9aa"
          },
          {
            "name": "Lead Count",
            "expression": [
              "",
              "IF(",
              "    SELECTEDVALUE(TimeSeries[Column1]) = \"YTD\",",
              "    0,",
              "    1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "85275db3-1afc-464a-8c68-4eb965ef3922"
          },
          {
            "name": "Open % Last 30 Days",
            "expression": [
              "",
              "IF(",
              "    CALCULATE(",
              "        COUNTROWS(",
              "            FILTER('MAINTENANCE_REQUEST_DAILY', 'MAINTENANCE_REQUEST_DAILY'[Opened On] >= TODAY() - 30 && 'MAINTENANCE_REQUEST_DAILY'[Opened On] < TODAY())),",
              "        'MAINTENANCE_REQUEST_DAILY'[Maintenance Request ID] <> BLANK()",
              "    ) = 0,",
              "    0,",
              "    DIVIDE(",
              "        CALCULATE(",
              "            COUNTROWS(",
              "                FILTER('MAINTENANCE_REQUEST_DAILY', 'MAINTENANCE_REQUEST_DAILY'[Opened On] < TODAY() && 'MAINTENANCE_REQUEST_DAILY'[Maintenance Status Type] IN {\"Open\", \"Suspended\"})),",
              "            'MAINTENANCE_REQUEST_DAILY'[Maintenance Request ID] <> BLANK()",
              "        ),",
              "        CALCULATE(",
              "            COUNTROWS(FILTER('MAINTENANCE_REQUEST_DAILY', 'MAINTENANCE_REQUEST_DAILY'[Opened On] >= TODAY() - 30 && 'MAINTENANCE_REQUEST_DAILY'[Opened On] < TODAY())),",
              "            'MAINTENANCE_REQUEST_DAILY'[Maintenance Request ID] <> BLANK()",
              "        )",
              "    )",
              ")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9e30287e-fb8f-44ce-9619-e72051b9bc97"
          },
          {
            "name": "Opened_date",
            "expression": [
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "03cfbb0b-138f-4902-9be8-4e4ef7a2cf90"
          }
        ],
        "partitions": [
          {
            "name": "MeasureExecutiveSummary",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PROPERTY_AGE_RECEIVABLES_MONTHLY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78f6dfc1-fc7d-495f-998b-c675876c8167",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5043388-e765-4cfc-9019-9759bda66ec1",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "420e80e6-2d3c-4462-a465-d17e445789f4",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d66d564d-8645-43b8-8d9e-7e3385bb1d46",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b61d677-fd55-4c64-9279-b777abc7868c",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f4b640d-1a47-477e-8b18-4f76c5011c45",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27c7330-231b-4d80-964c-0b018bfc4e2e",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15fb74d3-5b15-4dbd-88e4-b0866b8178b0",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8fe72b9-d983-4749-878a-9c71128e4efb",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9911864e-4127-4216-aa5d-d369d2ffe3aa",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "57a14900-5f18-4896-bd46-eaade0c0a876",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51c9a4fd-4030-4222-878e-a5a4ef2d0a91",
            "sourceColumn": "AR Code",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffcb5536-5f6d-4bb9-ae84-4803257ab611",
            "sourceColumn": "AR Code Type",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2aed45dc-ac7c-4d54-89a5-c1a09db8fde4",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "815eeaf3-4aad-4c10-b318-2b12812e6b85",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb48980d-a97e-419f-98ad-d058491228a8",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c689a5f-cc63-4665-bf81-63eb60dfa8f8",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61438669-f234-4696-ac78-732552d23b2e",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Unpaid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7d02fc73-4659-47cd-a55d-cf2a286339ec",
            "sourceColumn": "Unpaid",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 0 to 30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "717ec7a0-2026-4450-a516-eeb0e9c6ca0f",
            "sourceColumn": "Aged Receivables 0 to 30",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 31 to 60",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06d4dcc5-e784-48b5-8440-e79657cef61b",
            "sourceColumn": "Aged Receivables 31 to 60",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 61 to 90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5b8a4fd7-fee3-49f6-a37f-b24cbc028a61",
            "sourceColumn": "Aged Receivables 61 to 90",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 90+",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a77b3179-de54-4e23-951d-419635274ec1",
            "sourceColumn": "Aged Receivables 90+",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a35087a6-f60b-4a60-b432-94cb922e26bd",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7bb89ec2-c9e4-4e92-82f7-ca13052cc1ad",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "668ee836-9322-498f-b1c9-000ebb12adf6",
        "partitions": [
          {
            "name": "PROPERTY_AGE_RECEIVABLES_MONTHLY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    PROPERTY_AGE_RECEIVABLES_MONTHLY_View = DASHBOARD_Schema{[Name=\"PROPERTY_AGE_RECEIVABLES_MONTHLY\",Kind=\"View\"]}[Data]",
                "in",
                "    PROPERTY_AGE_RECEIVABLES_MONTHLY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEASE_PROGRESSION_DAILY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecd4eb64-29b5-4889-9c37-e78d36fd04f7",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9117fa04-81d7-4016-bd21-b6d39c249da9",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27dc59e0-fdfb-488b-a6a9-655882a8923e",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80d601d7-a216-4d0b-bba2-5bfe75611826",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18b02985-9073-4996-8e55-8bcd024dedbe",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdba58d7-42a3-4099-acc1-be5d78ea64d4",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90b576af-5584-434f-b558-da2da369d3ae",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac0a3171-906b-4e35-a308-7f169996d952",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90988823-538b-4ecf-ba9e-5ccac15e0801",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c1b8710-04f2-436b-9d4c-b2b1b0fd13f6",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3b6817e-1e2f-4e9b-9a1a-2611570a9bcd",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "92c6d229-0bba-46cd-af13-1cc03fed92ab",
            "sourceColumn": "Month Date",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "554aa485-6c33-4474-a669-174f09fd6d94",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "42cdcca6-71c8-4b92-a922-44130cc56e3a",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9323f379-5446-4519-b43a-0303e017be9f",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9066bc01-3081-44b4-91c2-c1aa1c1c2516",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0a07a563-66d8-40d4-8e5c-545380d5b66f",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5113dcff-5d6c-4931-b3e0-2a8951064d0d",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e82b1b1-ebfa-4d2f-ab7b-9e7c54b3791f",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf79b8bb-04a6-46c4-80cb-86af23dffd54",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "146041df-3bf7-468d-a446-c90fbf0c4104",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b28898ff-b849-4ff1-8dd2-bf957ddc1063",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Scheduled Move-in Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df4ab23c-6a85-4994-9b78-1405318908af",
            "sourceColumn": "Scheduled Move-in Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Performed Move-in Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8717c6e0-316f-4fa2-aa9f-780deb4db542",
            "sourceColumn": "Performed Move-in Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc5fca14-822b-443a-9211-4c8ae5882ebd",
            "sourceColumn": "Scheduled Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Performed Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1db26bb8-d5dd-4c31-b5ea-0377e1d2bfce",
            "sourceColumn": "Performed Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0dbbeb98-78de-4b35-9070-e17e10c89e20",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "952b5774-e325-4b56-802f-6f8eb7e5ef45",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b5d4099-d053-4791-9adb-a1e7ce14184a",
        "measures": [
          {
            "name": "Trail",
            "expression": "\"Trail\"",
            "lineageTag": "10151eb1-dbdb-4e8f-bfa3-dd917525f2ba"
          },
          {
            "name": "tt",
            "expression": "\"TT\"",
            "lineageTag": "8ad88da4-5ee4-4a47-ac9d-c63adf8c10db"
          }
        ],
        "partitions": [
          {
            "name": "LEASE_PROGRESSION_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    LEASE_PROGRESSION_DAILY_View = DASHBOARD_Schema{[Name=\"LEASE_PROGRESSION_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    LEASE_PROGRESSION_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TRANSACTION_CHARGES_COLLECTIONS_MONTHLY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "975b7fa4-f00e-4b81-9470-f21dab178fb8",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc66555e-82da-4fd2-8c9f-93037a1bd8cb",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fec6650-17d6-4375-904b-1843049c552c",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a780b13b-ac78-4dd4-9f22-e3fdb4576c77",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76526712-b33c-4e0f-9e2f-88fec691ed20",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c7c1163-90d5-4ec1-8f84-92ba0d0a78cf",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a90bbab0-c263-4b91-8ce9-9d623f4439c1",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "483f5402-958e-47c3-8a42-d3a4554e0926",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f44e58d7-3972-4cf3-9a00-e7ce8c511c83",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46f75053-d122-4f77-bfdb-fd837f78a3b1",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a60e6ee7-b908-4ee1-a431-8013e42f96b0",
            "sourceColumn": "Transaction ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f7821a7-45e3-4914-bde7-2c91ea947724",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "998607b6-83ee-428c-989a-ccfc4281a0dd",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08088722-dcec-4909-8ca0-4e1eeac94a3e",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "175a2033-29c7-4072-a59e-d510d9624696",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Post Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "85d4e471-f2ad-4288-8a87-e68d652cc2cf",
            "sourceColumn": "Post Month",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbb618e1-3158-4054-b55d-c65799a28b2f",
            "sourceColumn": "AR Code",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dcf15a3-5365-4122-ac66-5c4311755aeb",
            "sourceColumn": "AR Code Type",
            "summarizeBy": "none"
          },
          {
            "name": "Current Charges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca06b1bf-b54e-44b9-b868-7ad3e856f5c2",
            "sourceColumn": "Current Charges",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Receipts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cfb5e8fc-aa3a-4fa8-a83a-e006f41afee6",
            "sourceColumn": "Current Receipts",
            "summarizeBy": "sum"
          },
          {
            "name": "Prior Receipts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a95d94c7-080c-4da4-af2c-e7e01eadb187",
            "sourceColumn": "Prior Receipts",
            "summarizeBy": "sum"
          },
          {
            "name": "Credit Concessions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77344aa4-6bb5-4fc7-9b61-884198f173ee",
            "sourceColumn": "Credit Concessions",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "339e1158-f72b-4492-9beb-343ea177c7c8",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6c7b4556-e821-4009-9038-0fd6835cf817",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83b5f134-7602-4c66-9871-b7ccf67f7f9e",
        "partitions": [
          {
            "name": "TRANSACTION_CHARGES_COLLECTIONS_MONTHLY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY_View = DASHBOARD_Schema{[Name=\"TRANSACTION_CHARGES_COLLECTIONS_MONTHLY\",Kind=\"View\"]}[Data]",
                "in",
                "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEASE_EXPIRATION_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a80547ec-c9bc-42db-b1d3-d63a7f5079de",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c635dc32-a311-4700-876f-309db75165e4",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af924589-88a4-43a4-9d28-e4f006bc1565",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d8e178b-b6ff-48f2-94b7-4d970ed70d6a",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cc69b0b-078c-4bc8-9b76-18870c75f6b8",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afbd9a38-bc05-4f44-bd27-ce96a17cad0b",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e64138d-3902-421a-a2da-d2578e56dc2c",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6270c555-b992-4999-844d-9d032c6dc4d7",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4554355c-7d0c-4057-8212-278a9860b5c7",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd58177c-7bd1-4c6d-aa8e-81f99073a6a4",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf66c2b0-8561-4d16-9f56-68c63048c8bb",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7e0fa227-6f50-486b-bc60-b68d23418a97",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f7e9a299-52ae-46f4-aad3-533a9b1cd919",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Expiration Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e6e532b5-aa05-48ba-a606-0ad59a4e52ab",
            "sourceColumn": "Lease Expiration Date",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6d927ed-cd29-4d38-b7b2-25dc38de2fff",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7af27633-7d8f-4bb6-b205-21b6f7a744c0",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4268dde-95a9-4051-89d5-9acfdff5bccc",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7cc05253-8ce4-4dab-9fc5-27352dbc7f02",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d69664c-d651-4af6-bec1-c2881f21d4ec",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Expiration Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2567b266-5c07-4cc1-b626-d64341c1f6f7",
            "sourceColumn": "Expiration Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Renewal Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9c449b6-ed95-44a0-a2bd-d1a4776ddbf0",
            "sourceColumn": "Renewal Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3b24542-c3d2-4dd1-b802-429ab7d78be9",
            "sourceColumn": "Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Undecided Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "90b991eb-b270-4191-8f68-e7f03dc8e359",
            "sourceColumn": "Undecided Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "87057d5b-837c-4504-b9b8-516ca801405a",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "571e2684-1035-47c2-8c9b-20788b46137b",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c4c80b1e-bd5a-40cf-8817-0fc311a31731",
        "partitions": [
          {
            "name": "LEASE_EXPIRATION_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    LEASE_EXPIRATION_DAILY_View = DASHBOARD_Schema{[Name=\"LEASE_EXPIRATION_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    LEASE_EXPIRATION_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UNIT_SPACE_RENT_GROWTH_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa6ab946-412f-40f4-abbc-d01b6c5919dc",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c053958-98b3-403b-8573-2e7b34bc4e33",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a13f1cc-b327-4228-95c1-2f8072753efa",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05c4b6d4-cbd3-47b7-ad61-b80b4982e24c",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3394bb5-32e3-4dc6-a647-c0b2137407bf",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9628d91-bfb6-451b-9c9e-bb2978b8ad91",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bc0055e-22be-46b9-8dd3-74535cc0954d",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a0d4ef3-80e4-4e32-ab67-a34735203d66",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f7f49a-0462-4dea-87ca-d482ddbbb394",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01e0cfa8-ae12-41f5-9090-7b15bbbd8fba",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Space ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6788fb47-b019-4f93-9248-226b9d559617",
            "sourceColumn": "Unit Space ID",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "524ead43-01a5-4d8e-8e5a-ffa2ac4f1fa3",
            "sourceColumn": "Unit Number",
            "summarizeBy": "none"
          },
          {
            "name": "Floor Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "feef0e19-1d8f-4f22-b853-ac2cf89244cd",
            "sourceColumn": "Floor Plan",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Interval ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f297508d-8152-4ecf-994c-f9dc53838cad",
            "sourceColumn": "Lease Interval ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease Interval ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5ad0605-50e3-4866-8bad-b92de4444afa",
            "sourceColumn": "Prior Lease Interval ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Interval Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3345c668-43ef-44ac-b14f-f6e8e2ac47b7",
            "sourceColumn": "Lease Interval Type",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4bc386c3-0300-4e38-894e-c14f35a504af",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d8f73f90-b045-4d66-a86f-304089148c86",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e368ab6f-193c-4f01-b935-728f431f2756",
            "sourceColumn": "Prior Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9178d484-5f00-4b89-b26d-0d6fcdc6b999",
            "sourceColumn": "Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Prior Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d640d49-e2a8-47fb-8aed-4af9cc67314b",
            "sourceColumn": "Prior Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a47ead2-e0b2-49dd-8a86-d028e41263ac",
            "sourceColumn": "Prior Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ce68815-c18e-4893-aceb-4e8d3a789333",
            "sourceColumn": "Prior Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34d7696-b7a6-4db3-a0d3-2cd3a24c16d1",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c2bb1f-8ce6-4797-9000-555357f3b632",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66e1ce1a-ef28-4f99-91d7-4cca36a4491d",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8d50dc4-84b3-421d-b9f5-59cfe90d8463",
            "sourceColumn": "Prior Lease Term",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42341abc-27eb-4935-8b89-dc20ca93f060",
            "sourceColumn": "Lease Term",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2132d96-71d3-475d-b9e4-a116c48a4328",
            "sourceColumn": "Prior Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d2c2397-b7b9-40b3-9903-12f611bdadee",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "998bda88-9958-4285-a891-91dff309ccf7",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Effective Rent Per Sqft",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d56ffa14-a17c-4e2b-aaea-2a428e7e0ed8",
            "sourceColumn": "Prior Effective Rent Per Sqft",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Rent Per Sqft",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc05f1d7-7403-4752-8f04-9258d00857e0",
            "sourceColumn": "Effective Rent Per Sqft",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "beba8df7-8fc5-4614-bc07-a172168882da",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ebdacad9-fdec-47ee-b6ff-75819cd3bbcf",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c3ef5d57-0d3b-44eb-beb2-7dc7644f812d",
        "partitions": [
          {
            "name": "UNIT_SPACE_RENT_GROWTH_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    UNIT_SPACE_RENT_GROWTH_DAILY_View = DASHBOARD_Schema{[Name=\"UNIT_SPACE_RENT_GROWTH_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    UNIT_SPACE_RENT_GROWTH_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEAD_SOURCE_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d04b4b1-700b-40a6-aca6-f491ff3ba5c7",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "330a2248-d26d-4c35-b569-98a0e7439956",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33b0b6d3-4fe0-45bd-8636-5e17b4c8dee9",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b446d2a2-98a9-41ca-9ff9-3457cbb5a2b0",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c62e317-5443-4e73-8ef0-0b700f293e87",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "581d1b96-0acb-4e91-b30c-a2a77faac55c",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed3a3596-ce14-48a4-9f7d-f282195c9efe",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3815f56a-5d13-4278-8c42-11425b752b5e",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "181d64f4-817d-4277-bac6-8ed75a5628e2",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93f52c19-5e13-4691-94f6-931d297e2b5c",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lead ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85015b11-40a0-4444-a1bb-241e51d18f08",
            "sourceColumn": "Lead ID",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0dfb37e3-c43f-46a6-bfb6-55802d34615d",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Event Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5cd98351-0908-4529-9258-09e6c50b47c7",
            "sourceColumn": "Event Time",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8752a1e6-fa2e-4527-b657-572f033c3621",
            "sourceColumn": "Lead Source",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca337fcd-18c0-4e04-a4d4-7450e9045248",
            "sourceColumn": "Lead Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Move In",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a7ee0abc-86ad-46ed-841f-2e796c6cbb4f",
            "sourceColumn": "Move In",
            "summarizeBy": "sum"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "59f5b63a-eace-4374-ba15-717461b70da6",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09bbaa3b-46d4-4b02-b708-6a025a49a980",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cccd6472-8877-4420-b319-bc5b0d408d6f",
            "sourceColumn": "Customer First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2dd383b-3bfe-4b21-a645-0f4513d5ba46",
            "sourceColumn": "Customer Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62d60205-e2f2-4e67-a166-7594b3fd0296",
            "sourceColumn": "Lead Status",
            "summarizeBy": "none"
          },
          {
            "name": "Leasing Agent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d69111c-b362-4567-8062-37a3bb03d4b2",
            "sourceColumn": "Leasing Agent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Original Contact Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a641c86-d111-4633-a8df-11e315c1859e",
            "sourceColumn": "Original Contact Method",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "234ab576-0ccf-4220-8790-9c6ec202290b",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Application Started Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aaf7306b-31b3-48a6-bb5a-bd5ed2162928",
            "sourceColumn": "Application Started Date",
            "summarizeBy": "none"
          },
          {
            "name": "First Visit/Tour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e0961581-2729-4f90-81b4-fbb9f5c1e7eb",
            "sourceColumn": "First Visit/Tour",
            "summarizeBy": "none"
          },
          {
            "name": "Application Completed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "23fcc62d-42a9-409a-8975-e3502b1530d6",
            "sourceColumn": "Application Completed Date",
            "summarizeBy": "none"
          },
          {
            "name": "Application Approved Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "79cddfb8-b1ea-451c-b140-f0a873850933",
            "sourceColumn": "Application Approved Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2595694c-1c9d-4578-92cb-f4960fcd804f",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Completed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0a69b2b5-e25b-403a-9b35-854a3657ae97",
            "sourceColumn": "Lease Completed Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Approved Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "10a37792-21cf-4a6c-851b-44e089b20cb4",
            "sourceColumn": "Lease Approved Date",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "cab160f3-c429-45f7-a03e-587f2e2b8442",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c1a69966-6da2-4e93-9e7f-0eeaeab2659e",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e8dae403-85ac-4a3b-afe8-22c42a6d5e49",
        "partitions": [
          {
            "name": "LEAD_SOURCE_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    LEAD_SOURCE_DAILY_View = DASHBOARD_Schema{[Name=\"LEAD_SOURCE_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    LEAD_SOURCE_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MAINTENANCE_REQUEST_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba0cbf30-a02b-43ac-84f2-d9acd497db11",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a3066ca-960e-432a-b230-ba2925a7ab15",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "777b2bac-1839-486c-a26e-a7ccdbcbcb53",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "612282d8-80be-4f59-adb6-257dd686924e",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e99c317a-235f-4ca5-be59-93154a12fc67",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aec9574-5bcb-4cd7-8c74-fde210f7d279",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f20006ae-175b-4a21-8e6f-e9019fd2b184",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "528d56c7-6549-4a5e-99c2-d0b19cb3d81c",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b60fba29-1cc9-4f4a-85dd-f8d8ca32010d",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2907503f-0c3e-47c5-a02a-8ef9e744f0ad",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858c1e99-0a60-466f-b83a-88834634bc56",
            "sourceColumn": "Maintenance Request ID",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Request Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e108c521-9258-4f7e-8d0d-f1de60d82142",
            "sourceColumn": "Maintenance Request Type",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Priority Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "812bb9a5-1b90-4e57-b0b3-e0af257eba8a",
            "sourceColumn": "Maintenance Priority Type",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Status Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1793b0bd-9f9b-4a18-b194-1f565c4a895d",
            "sourceColumn": "Maintenance Status Type",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c8ae490-eb08-4808-8a78-8228f0908b23",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b96c68ea-7bdb-425f-a6e7-26ed0074c017",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Reference ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39e0786a-89d3-4aed-876c-67622fdef7ee",
            "sourceColumn": "Reference ID",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51f3f655-0d4a-4d96-82eb-8a5b95d95e56",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Created By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04759eb1-75b5-492a-a2fb-cb03effbba74",
            "sourceColumn": "Created By",
            "summarizeBy": "none"
          },
          {
            "name": "Closed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4011d4f4-b344-48f1-ac2d-ea40cc9bad8e",
            "sourceColumn": "Closed By",
            "summarizeBy": "none"
          },
          {
            "name": "Problem Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5782d8d-f435-49bb-93b5-4597b47106af",
            "sourceColumn": "Problem Location",
            "summarizeBy": "none"
          },
          {
            "name": "Origin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3ff485b-2026-4786-953c-50f233eee489",
            "sourceColumn": "Origin",
            "summarizeBy": "none"
          },
          {
            "name": "Opened On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d573c15e-0d0e-44f3-b735-d10c28955f50",
            "sourceColumn": "Opened On",
            "summarizeBy": "none"
          },
          {
            "name": "Completed On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8efaaa07-c405-45d9-9ffa-e8122e9dbade",
            "sourceColumn": "Completed On",
            "summarizeBy": "none"
          },
          {
            "name": "Hours To Close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "312c28d2-8a15-4ec5-835a-778a2b3475e5",
            "sourceColumn": "Hours To Close",
            "summarizeBy": "sum"
          },
          {
            "name": "Suspended Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1458d4ec-66dc-49e3-8b3f-1aad7ff407bb",
            "sourceColumn": "Suspended Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Completed Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ee14eca-168c-49cc-b555-09ce4d957145",
            "sourceColumn": "Completed Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Cancelled Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46086b48-5241-4f33-bc9a-bae5a0af758e",
            "sourceColumn": "Cancelled Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4ca5894f-8a2d-431a-ada3-5d24f9fe366e",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4dbbf40a-2d45-46e0-ac9a-86eefcef030f",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "MonthFormatted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT('MAINTENANCE_REQUEST_DAILY'[Opened On], \"MMMM\")",
              ""
            ],
            "lineageTag": "ebc7f61b-bc8d-4b26-baf7-652329e7c41e",
            "sortByColumn": "MonthNumber",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "MONTH('MAINTENANCE_REQUEST_DAILY'[Opened On])",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "831b4690-ad3e-49a1-bcfc-af33ae3f8ca2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "FORMAT('MAINTENANCE_REQUEST_DAILY'[Opened On], \"YYYY-MM\")",
              ""
            ],
            "formatString": "yyyy-mm",
            "lineageTag": "5794ca79-cbf7-4179-864d-bb6b8fa5ae1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT('MAINTENANCE_REQUEST_DAILY'[Opened On], \"YYYY-MM\")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "512c9620-545b-4b6c-9205-f1c38293fadb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "70d5f44c-d824-42a1-b2db-eb73cefa0f94",
        "partitions": [
          {
            "name": "MAINTENANCE_REQUEST_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    MAINTENANCE_REQUEST_DAILY_View = DASHBOARD_Schema{[Name=\"MAINTENANCE_REQUEST_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    MAINTENANCE_REQUEST_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TimeSeries",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61b3b3a2-d5be-4104-811a-82559adbac11",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "81e2d0b9-7bde-4193-971e-311016b0e544",
        "partitions": [
          {
            "name": "TimeSeries",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WigxxUYrViVbyhdKBUDocRMcCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "51bda72478e5407ebee92fee1c304cd0"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e4419c14-8424-4b98-8a5a-2cef82294919",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "de48eb1c-b50c-4bff-9d08-6051ad52a86a",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "26e7a501-f607-4e2d-875a-f611088a435c",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7e098111-2c79-4395-b48e-5d676c950809",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Column1\", NAMEOF('TimeSeries'[Column1]), 0)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}