{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"UNIT_OCCUPANCY_DAILY\",\"PROPERTY_AGE_RECEIVABLES_MONTHLY\",\"LEASE_PROGRESSION_DAILY\",\"TRANSACTION_CHARGES_COLLECTIONS_MONTHLY\",\"Measure Asset Management\",\"NOI_MONTHLY\",\"MAINTENANCE_REQUEST_DAILY\",\"UNIT_SPACE_RENT_GROWTH_DAILY\",\"LEASE_EXPIRATION_DAILY\",\"Measure Property Performance\",\"LEAD_SOURCE_DAILY\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "unit_occupancy_daily.month_evnt": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Month Evnt"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Month": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "unit_occupancy_daily.quarter_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Quarter Year"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "QtrYear": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "unit_occupancy_daily.weekday_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "UNIT_OCCUPANCY_DAILY",
                    "ConceptualProperty": "Weekday 1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Weekday": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "UNIT_OCCUPANCY_DAILY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fface54f-9256-40da-8423-6b9377db46a6",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "725b9bb7-c8c5-4e39-a0d0-8e4184676075",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c99ab5b7-5fed-4555-a134-883faa245376",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b472742-5074-4e4a-b756-f9ab04684986",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96da28b8-fb19-424c-92e6-cc7c50c004da",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c4e2628-dbae-4a7f-af01-df3f8d398646",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3b9ea98-eee0-4884-88da-4c6c18bc3b56",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "083740af-ccba-4c9c-a963-97f0c62a46ad",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cbac884-02dc-4210-8033-095e12895b2d",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e627cf50-5c1f-4f0a-97c2-4eb51f4fcc45",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3efca71-dede-4b89-a5d4-c50c5df87abb",
            "sourceColumn": "Unit Type",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3b92ec6-dab4-446b-a251-7cfd9348f323",
            "sourceColumn": "Unit Number",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31cea10d-117f-41a2-8c46-661473782e9f",
            "sourceColumn": "Unit Status",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e7f44d0-a6ff-41ff-aba8-12d5fc4c71a6",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "309d40e2-5411-467f-bada-48812a90855b",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Model Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9df64f21-a360-43b2-9750-5d564b2b74d1",
            "sourceColumn": "Model Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Down Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2a209667-b5db-4968-bae2-a4fdbcb8cb16",
            "sourceColumn": "Down Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52e157a8-fdfa-4965-9d90-a18aa9ff3004",
            "sourceColumn": "Rentable Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Occupied Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3b5e693-83f9-4b00-a971-1f8929e46388",
            "sourceColumn": "Occupied Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Vacant Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20db4e1d-ac98-4cb0-b47a-e4e8111a57c8",
            "sourceColumn": "Rentable Vacant Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Leased Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b863ea5f-48a4-4d05-8e00-2b26d5419a16",
            "sourceColumn": "Rentable Leased Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "806c4f52-de4d-464c-aac0-33dc4459b8e2",
            "sourceColumn": "Rentable Trend Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Exposed Unit Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e828637-11eb-45d4-a15a-27f7f1715f0c",
            "sourceColumn": "Rentable Exposed Unit Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend 30 Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0c87bff-e548-4b0a-b272-d7d4164d993e",
            "sourceColumn": "Rentable Trend 30 Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Rentable Trend 60 Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ef42efc-6fc2-4dd5-9f64-bf26d44da8b2",
            "sourceColumn": "Rentable Trend 60 Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Unrented Not Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dc642b20-595c-4551-8902-c1658267fee2",
            "sourceColumn": "Vacant Unrented Not Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Unrented Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d79e1eb1-bdb1-428b-a36c-b231d2f8e15b",
            "sourceColumn": "Vacant Unrented Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Rented Not Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65807fe5-a688-4212-8b65-011fce1840ac",
            "sourceColumn": "Vacant Rented Not Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Rented Ready Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f88c1ed-a5b0-4952-a0fa-6df484823744",
            "sourceColumn": "Vacant Rented Ready Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ce81d49-93f1-4e8f-a139-8234683418a5",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98d00e06-9950-4928-b18f-5dd8a5403503",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a1d6258-e140-43dc-b7b9-29d69de9eb51",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f970ed1-303d-405b-b095-e02f58ee305a",
            "sourceColumn": "Future Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ad36b67-874d-4a4c-bedc-1de0ff922dd4",
            "sourceColumn": "Future Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Future Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32eb216a-ae13-4642-883e-6682e2bee23e",
            "sourceColumn": "Future Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1e95f4f-c238-4b3a-80d1-abc19db4df4c",
            "sourceColumn": "Prior Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "952fde0d-0383-42fd-9081-34e7098e556a",
            "sourceColumn": "Prior Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9efdbad-ec26-43db-a538-06d61f1d7845",
            "sourceColumn": "Prior Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aee4222-02d4-4fe9-84b3-c2495a46dbbb",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Future Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "462f25f2-0a40-4bb9-a410-fdbf8ddd2e48",
            "sourceColumn": "Future Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2fd82a6-15df-4797-ae26-f073941890a0",
            "sourceColumn": "Prior Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Future Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9934293b-6d5f-4c45-8aec-d155c3a41615",
            "sourceColumn": "Future Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ea7af308-0b4e-4f3c-848d-6e15450745b8",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8951790c-69e8-4f00-a7f1-bb72eb54d6d2",
            "sourceColumn": "Prior Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "45b363f4-12cb-43b5-9a7e-25df0ea8493d",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ee37eb79-d284-4bf5-9260-b789432d8ab7",
            "sourceColumn": "Prior Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Days Vacant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2a4f32c-0d1b-4f95-bf61-83f307c88810",
            "sourceColumn": "Days Vacant",
            "summarizeBy": "sum"
          },
          {
            "name": "Notice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "645afc94-60fc-4e12-a74d-2fea51568662",
            "sourceColumn": "Notice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Notice Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f26f39b4-45b4-4a97-b15a-0baa2ded90cf",
            "sourceColumn": "Prior Notice Date",
            "summarizeBy": "none"
          },
          {
            "name": "Leased Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d47da580-7ead-4566-858b-e7d399b0728a",
            "sourceColumn": "Leased Date",
            "summarizeBy": "none"
          },
          {
            "name": "Vacant Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "83e23965-8eb5-41d4-8466-4785200c90ba",
            "sourceColumn": "Vacant Date",
            "summarizeBy": "none"
          },
          {
            "name": "Occupied Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "fedc3c3d-b8de-45ce-a4eb-422a1408c0bc",
            "sourceColumn": "Occupied Date",
            "summarizeBy": "none"
          },
          {
            "name": "Square Feet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0bd00652-f685-4055-8e37-d5a9d35e84a8",
            "sourceColumn": "Square Feet",
            "summarizeBy": "sum"
          },
          {
            "name": "Bedroom Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c2c9a607-1730-4357-9f1d-0da16a4e6817",
            "sourceColumn": "Bedroom Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Bathroom Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "42659876-3aff-4ead-8102-ef12a65ea17d",
            "sourceColumn": "Bathroom Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Make Ready Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f2b2eefa-eb29-45a6-95a9-1f3fa2f61c8f",
            "sourceColumn": "Make Ready Date",
            "summarizeBy": "none"
          },
          {
            "name": "Available On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f0469a36-7f39-4204-aab4-a311ec38dbdc",
            "sourceColumn": "Available On",
            "summarizeBy": "none"
          },
          {
            "name": "Budgeted Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7e116ab0-f44e-4516-b1de-04cca5e4aebd",
            "sourceColumn": "Budgeted Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Current MTM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a1c7bed4-4a37-4a1c-b138-ff39917e7628",
            "sourceColumn": "Current MTM",
            "summarizeBy": "sum"
          },
          {
            "name": "Vacant Units",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d97e3070-1294-4d7e-91ea-370de62ea40c",
            "sourceColumn": "Vacant Units",
            "summarizeBy": "sum"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "382001ec-2c4d-4c8d-95eb-955ecc71f847",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bb5307a3-988d-4732-95bf-d4b69b9d0505",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d9293ff-0be9-49c2-8b32-be13f103776c",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Floor Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29d60680-eed6-4a04-b839-9935957d5a4a",
            "sourceColumn": "Floor Plan",
            "summarizeBy": "none"
          },
          {
            "name": "Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f1778e8-5af0-4f1a-b8f0-3c05671fea0a",
            "sourceColumn": "Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "440a1ccc-62d8-4cca-8830-7d42611a7fd4",
            "sourceColumn": "Scheduled Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Charges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "415dd021-f4bc-464e-99e0-85bde93e335e",
            "sourceColumn": "Scheduled Charges",
            "summarizeBy": "sum"
          },
          {
            "name": "Market Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef3dd850-b4eb-4ddc-9757-565e70d104a0",
            "sourceColumn": "Market Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Days On Market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cea17276-30ea-4c79-954b-b7d4154f79e4",
            "sourceColumn": "Days On Market",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c93ecd1c-8f5e-45f7-b80d-1f6e135785ba",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9ceaef4a-9fc4-43dc-b44a-4b6f841df994",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-1,\"Current\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-8,\"-7\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-15,\"-14\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-22,\"-21\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-29,\"-28\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-31,\"-30\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-61,\"-60\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+6,\"+7\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+13,\"+14\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+20,\"+21\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+27,\"+28\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+31,\"+30\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+61,\"+60\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+91,\"+90\",",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()+121,\"+120\"",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4cda86b3-a1fc-4248-b9c1-6fff805de009",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "YEAR(UNIT_OCCUPANCY_DAILY[Event Date])&\"  Q\"&QUARTER(UNIT_OCCUPANCY_DAILY[Event Date])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "acef4278-57e2-4ec2-989d-3e14e2d8b26e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month Evnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(UNIT_OCCUPANCY_DAILY[Event Date],\"MMM\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bdc2f40b-cc11-400a-88b4-b260cfd9976f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthYearnum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "FORMAT(",
              "    UNIT_OCCUPANCY_DAILY[Event Date],",
              "    \"YYYYMM\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "81055a53-eb7a-4c2f-9924-24ffea40056e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "6999991a-40fe-4401-8aad-0f8071b423cd",
        "partitions": [
          {
            "name": "UNIT_OCCUPANCY_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"Compute_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    UNIT_OCCUPANCY_DAILY_View = DASHBOARD_Schema{[Name=\"UNIT_OCCUPANCY_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    UNIT_OCCUPANCY_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MeasureExecutiveSummary",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d2d94abeca3645c0ade22dccca6c74b4"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "65a78f37-f24b-4d62-a22b-0808cc5bcf72",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3178b282-5cf3-455a-bd5f-c448568f2b62",
        "measures": [
          {
            "name": "Occupancy %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Occupied Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f56caa7e-67ca-4837-b672-d58da31dc15a"
          },
          {
            "name": "Leased %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Leased Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "82932ffc-9d8f-418e-86eb-99518aafc7ce"
          },
          {
            "name": "Exposed %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Exposed Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "89e96319-6d09-4726-bc0b-e05027c7af96"
          },
          {
            "name": "Net Performed Move-Ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(LEASE_PROGRESSION_DAILY[Performed Move-in Count])-sum(LEASE_PROGRESSION_DAILY[Performed Move-out Count])"
            ],
            "lineageTag": "3b3a9b68-6705-463c-8447-812697706767"
          },
          {
            "name": "Current Month Net Move Ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(LEASE_PROGRESSION_DAILY[Performed Move-in Count]),",
              "    LEASE_PROGRESSION_DAILY[Event Date]>=TODAY())",
              "-",
              "CALCULATE(",
              "    SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-out Count]),",
              "    LEASE_PROGRESSION_DAILY[Event Date]>=TODAY())",
              ""
            ],
            "lineageTag": "10dc7c67-9e60-4a8f-9265-b3e59666fb8e"
          },
          {
            "name": "Net Scheduled Move-ins",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-in Count])-SUM(LEASE_PROGRESSION_DAILY[Scheduled Move-out Count])"
            ],
            "lineageTag": "93d4225e-9270-4eac-af92-ab0b0bde1d44"
          },
          {
            "name": "Trend %",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Trend Unit Count]),",
              "    SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f54c80ee-6a27-4975-a872-2219e58f629f"
          },
          {
            "name": "60th Day",
            "expression": [
              "",
              "CALCULATE(",
              "    [Occupancy %],",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-60",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d3f12397-4687-4463-b3f2-3c794ca38e81"
          },
          {
            "name": "30th Day",
            "expression": [
              "",
              "CALCULATE(",
              "    [Occupancy %],",
              "    UNIT_OCCUPANCY_DAILY[Event Date]=TODAY()-30",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e4170bb0-3dfc-483a-adf0-a617bc3077ce"
          },
          {
            "name": "Weekday",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-1,\"Current\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-8,\"-7\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-15,\"-14\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-22,\"-21\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-29,\"-28\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-31,\"-30\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()-61,\"-60\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+6,\"+7\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+13,\"+14\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+20,\"+21\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+27,\"+28\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+31,\"+30\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+61,\"+60\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+91,\"+90\",",
              "    SELECTEDVALUE(LEASE_PROGRESSION_DAILY[Event Date])=TODAY()+121,\"+120\"",
              "    )"
            ],
            "lineageTag": "b1675ba6-1ff3-4fac-8cec-6cc2c02ce02d"
          },
          {
            "name": "WeekdayColor",
            "expression": [
              "",
              "SWITCH(",
              "    SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Weekday 1]),",
              "    \"Current\",\"#9D6E9C\",",
              "    \"-7\",\"#C6ABC6\",\"-14\",\"#C6ABC6\",\"-21\",\"#C6ABC6\",\"-28\",\"#C6ABC6\",\"-30\",\"#C6ABC6\", \"-60\",\"#C6ABC6\",",
              "    \"+7\",\"#E0E0E0\",\"+14\",\"#E0E0E0\",\"+21\",\"#E0E0E0\",\"+28\",\"#E0E0E0\",\"+30\",\"#E0E0E0\",\"+60\",\"#E0E0E0\",\"+120\",\"#E0E0E0\",\"+90\",\"#E0E0E0\")",
              ""
            ],
            "lineageTag": "bb25125a-390a-4647-b7a2-ff0da77d46d8"
          },
          {
            "name": "Avg Occupancy",
            "expression": [
              "",
              "DIVIDE(",
              "    AVERAGE(UNIT_OCCUPANCY_DAILY[Occupied Unit Count]),",
              "    AVERAGE(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "33ea18d0-9503-4ae2-b74a-71e299020f45"
          },
          {
            "name": "% Collected",
            "expression": [
              "",
              "DIVIDE(",
              "    SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts])+SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts]),",
              "    SUM(TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges]),",
              "    0",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cb683e03-1bb4-4ee3-b8f7-ee21996ab25e"
          },
          {
            "name": "Uncollected",
            "expression": [
              "",
              "SUMX(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY,",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges]-((TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts]+TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts])+TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Credit Concessions]))"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "e65741aa-27e5-4ba9-82ff-aa4cbc5df4bf"
          }
        ],
        "partitions": [
          {
            "name": "MeasureExecutiveSummary",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "PROPERTY_AGE_RECEIVABLES_MONTHLY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78f6dfc1-fc7d-495f-998b-c675876c8167",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5043388-e765-4cfc-9019-9759bda66ec1",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "420e80e6-2d3c-4462-a465-d17e445789f4",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d66d564d-8645-43b8-8d9e-7e3385bb1d46",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b61d677-fd55-4c64-9279-b777abc7868c",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f4b640d-1a47-477e-8b18-4f76c5011c45",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27c7330-231b-4d80-964c-0b018bfc4e2e",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15fb74d3-5b15-4dbd-88e4-b0866b8178b0",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8fe72b9-d983-4749-878a-9c71128e4efb",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9911864e-4127-4216-aa5d-d369d2ffe3aa",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "57a14900-5f18-4896-bd46-eaade0c0a876",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51c9a4fd-4030-4222-878e-a5a4ef2d0a91",
            "sourceColumn": "AR Code",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffcb5536-5f6d-4bb9-ae84-4803257ab611",
            "sourceColumn": "AR Code Type",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2aed45dc-ac7c-4d54-89a5-c1a09db8fde4",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "815eeaf3-4aad-4c10-b318-2b12812e6b85",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb48980d-a97e-419f-98ad-d058491228a8",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c689a5f-cc63-4665-bf81-63eb60dfa8f8",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61438669-f234-4696-ac78-732552d23b2e",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Unpaid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7d02fc73-4659-47cd-a55d-cf2a286339ec",
            "sourceColumn": "Unpaid",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 0 to 30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "717ec7a0-2026-4450-a516-eeb0e9c6ca0f",
            "sourceColumn": "Aged Receivables 0 to 30",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 31 to 60",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "06d4dcc5-e784-48b5-8440-e79657cef61b",
            "sourceColumn": "Aged Receivables 31 to 60",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 61 to 90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5b8a4fd7-fee3-49f6-a37f-b24cbc028a61",
            "sourceColumn": "Aged Receivables 61 to 90",
            "summarizeBy": "sum"
          },
          {
            "name": "Aged Receivables 90+",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a77b3179-de54-4e23-951d-419635274ec1",
            "sourceColumn": "Aged Receivables 90+",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a35087a6-f60b-4a60-b432-94cb922e26bd",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7bb89ec2-c9e4-4e92-82f7-ca13052cc1ad",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "AgeReceivable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "\"Age Receivable Buckets\""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e2a7928f-5438-4780-b946-fd23996e5fa9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "668ee836-9322-498f-b1c9-000ebb12adf6",
        "partitions": [
          {
            "name": "PROPERTY_AGE_RECEIVABLES_MONTHLY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    PROPERTY_AGE_RECEIVABLES_MONTHLY_View = DASHBOARD_Schema{[Name=\"PROPERTY_AGE_RECEIVABLES_MONTHLY\",Kind=\"View\"]}[Data]",
                "in",
                "    PROPERTY_AGE_RECEIVABLES_MONTHLY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEASE_PROGRESSION_DAILY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecd4eb64-29b5-4889-9c37-e78d36fd04f7",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9117fa04-81d7-4016-bd21-b6d39c249da9",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27dc59e0-fdfb-488b-a6a9-655882a8923e",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80d601d7-a216-4d0b-bba2-5bfe75611826",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18b02985-9073-4996-8e55-8bcd024dedbe",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdba58d7-42a3-4099-acc1-be5d78ea64d4",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90b576af-5584-434f-b558-da2da369d3ae",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac0a3171-906b-4e35-a308-7f169996d952",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90988823-538b-4ecf-ba9e-5ccac15e0801",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c1b8710-04f2-436b-9d4c-b2b1b0fd13f6",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3b6817e-1e2f-4e9b-9a1a-2611570a9bcd",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Month Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "92c6d229-0bba-46cd-af13-1cc03fed92ab",
            "sourceColumn": "Month Date",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "554aa485-6c33-4474-a669-174f09fd6d94",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "42cdcca6-71c8-4b92-a922-44130cc56e3a",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9323f379-5446-4519-b43a-0303e017be9f",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9066bc01-3081-44b4-91c2-c1aa1c1c2516",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0a07a563-66d8-40d4-8e5c-545380d5b66f",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5113dcff-5d6c-4931-b3e0-2a8951064d0d",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e82b1b1-ebfa-4d2f-ab7b-9e7c54b3791f",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf79b8bb-04a6-46c4-80cb-86af23dffd54",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "146041df-3bf7-468d-a446-c90fbf0c4104",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b28898ff-b849-4ff1-8dd2-bf957ddc1063",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Scheduled Move-in Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df4ab23c-6a85-4994-9b78-1405318908af",
            "sourceColumn": "Scheduled Move-in Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Performed Move-in Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8717c6e0-316f-4fa2-aa9f-780deb4db542",
            "sourceColumn": "Performed Move-in Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Scheduled Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc5fca14-822b-443a-9211-4c8ae5882ebd",
            "sourceColumn": "Scheduled Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Performed Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1db26bb8-d5dd-4c31-b5ea-0377e1d2bfce",
            "sourceColumn": "Performed Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0dbbeb98-78de-4b35-9070-e17e10c89e20",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "952b5774-e325-4b56-802f-6f8eb7e5ef45",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b5d4099-d053-4791-9adb-a1e7ce14184a",
        "measures": [
          {
            "name": "Trail",
            "expression": "\"Trail\"",
            "lineageTag": "10151eb1-dbdb-4e8f-bfa3-dd917525f2ba"
          },
          {
            "name": "tt",
            "expression": "\"TT\"",
            "lineageTag": "8ad88da4-5ee4-4a47-ac9d-c63adf8c10db"
          }
        ],
        "partitions": [
          {
            "name": "LEASE_PROGRESSION_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    LEASE_PROGRESSION_DAILY_View = DASHBOARD_Schema{[Name=\"LEASE_PROGRESSION_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    LEASE_PROGRESSION_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TRANSACTION_CHARGES_COLLECTIONS_MONTHLY",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "975b7fa4-f00e-4b81-9470-f21dab178fb8",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc66555e-82da-4fd2-8c9f-93037a1bd8cb",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fec6650-17d6-4375-904b-1843049c552c",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a780b13b-ac78-4dd4-9f22-e3fdb4576c77",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76526712-b33c-4e0f-9e2f-88fec691ed20",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c7c1163-90d5-4ec1-8f84-92ba0d0a78cf",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a90bbab0-c263-4b91-8ce9-9d623f4439c1",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "483f5402-958e-47c3-8a42-d3a4554e0926",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f44e58d7-3972-4cf3-9a00-e7ce8c511c83",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46f75053-d122-4f77-bfdb-fd837f78a3b1",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a60e6ee7-b908-4ee1-a431-8013e42f96b0",
            "sourceColumn": "Transaction ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f7821a7-45e3-4914-bde7-2c91ea947724",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "998607b6-83ee-428c-989a-ccfc4281a0dd",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08088722-dcec-4909-8ca0-4e1eeac94a3e",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "175a2033-29c7-4072-a59e-d510d9624696",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Post Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "85d4e471-f2ad-4288-8a87-e68d652cc2cf",
            "sourceColumn": "Post Month",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbb618e1-3158-4054-b55d-c65799a28b2f",
            "sourceColumn": "AR Code",
            "summarizeBy": "none"
          },
          {
            "name": "AR Code Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dcf15a3-5365-4122-ac66-5c4311755aeb",
            "sourceColumn": "AR Code Type",
            "summarizeBy": "none"
          },
          {
            "name": "Current Charges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca06b1bf-b54e-44b9-b868-7ad3e856f5c2",
            "sourceColumn": "Current Charges",
            "summarizeBy": "sum"
          },
          {
            "name": "Current Receipts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cfb5e8fc-aa3a-4fa8-a83a-e006f41afee6",
            "sourceColumn": "Current Receipts",
            "summarizeBy": "sum"
          },
          {
            "name": "Prior Receipts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a95d94c7-080c-4da4-af2c-e7e01eadb187",
            "sourceColumn": "Prior Receipts",
            "summarizeBy": "sum"
          },
          {
            "name": "Credit Concessions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77344aa4-6bb5-4fc7-9b61-884198f173ee",
            "sourceColumn": "Credit Concessions",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "339e1158-f72b-4492-9beb-343ea177c7c8",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6c7b4556-e821-4009-9038-0fd6835cf817",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83b5f134-7602-4c66-9871-b7ccf67f7f9e",
        "partitions": [
          {
            "name": "TRANSACTION_CHARGES_COLLECTIONS_MONTHLY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY_View = DASHBOARD_Schema{[Name=\"TRANSACTION_CHARGES_COLLECTIONS_MONTHLY\",Kind=\"View\"]}[Data]",
                "in",
                "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Asset Management",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "1026c5c4-ce74-4c28-b805-83cb60478c50",
        "measures": [
          {
            "name": "Exposed %1",
            "expression": [
              "",
              "VAR SumRentableUnitCount =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              ")",
              "var SumRentableExposedUnitCount =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Rentable Exposed Unit Count]",
              ")",
              "RETURN",
              "IF(",
              "    SumRentableUnitCount=0,",
              "    0,",
              "    DIVIDE(",
              "        SumRentableExposedUnitCount,",
              "        SumRentableUnitCount",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bdad1f3f-4090-4a08-b8c1-65964467fbdd"
          },
          {
            "name": "NOI Actual",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(NOI_MONTHLY[Actual Amount]),",
              "    NOI_MONTHLY[GL Account Type Name]=\"Income\" && NOI_MONTHLY[NOI GL Group]=\"Net Income/(Loss)\"",
              "    && YEAR(NOI_MONTHLY[Post Month])=YEAR(TODAY()) && NOI_MONTHLY[Post Month]<TODAY()",
              "    )",
              "    -",
              " CALCULATE(",
              "       SUM(NOI_MONTHLY[Actual Amount]),",
              "       NOI_MONTHLY[GL Account Type Name]=\"Expense\" && NOI_MONTHLY[NOI GL Group]=\"Net Income/(Loss)\"",
              "       && YEAR(NOI_MONTHLY[Post Month])=YEAR(TODAY()) && NOI_MONTHLY[Post Month]<TODAY()",
              "       )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "0197beb5-09e9-48e7-bc44-97a40e587d2d"
          },
          {
            "name": "Avg In-Place Rent PSF",
            "expression": [
              "",
              "VAR TotalSquareFeet =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Square Feet]",
              ")",
              "VAR TotalScheduledRent =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Scheduled Rent]",
              ")",
              "RETURN",
              "IF(",
              "    TotalSquareFeet = 0,0,",
              "    DIVIDE(",
              "        TotalScheduledRent,",
              "        TotalSquareFeet",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "6586b6d2-6b06-4c2d-9767-94ab58ab4135"
          },
          {
            "name": "Avg Market Rent PSF",
            "expression": [
              "",
              "VAR TotalSquareFeet =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Square Feet]",
              ")",
              "VAR TotalMarketRent =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Market Rent]",
              ")",
              "RETURN",
              "IF(",
              "    TotalSquareFeet=0,0,",
              "    DIVIDE(",
              "        TotalMarketRent,",
              "        TotalSquareFeet",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "f9f086ed-e9f5-4b32-ae54-2c449a0a7b6b"
          },
          {
            "name": "Is_NOI",
            "expression": [
              "",
              "IF(",
              "    SELECTEDVALUE(",
              "        NOI_MONTHLY[NOI GL Group] ",
              "    ) = \"Net Income/(Loss)\",",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "67f41fea-6daa-48b7-9081-6b26f1234f0a"
          },
          {
            "name": "AAMOUNT",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(",
              "        NOI_MONTHLY[Actual Amount]",
              "    ),",
              "    NOI_MONTHLY[Post Month] >= DATE(2024,1,1) &&",
              "    NOI_MONTHLY[Post Month] <= DATE(2024,12,31)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4555b5a3-dfac-45a8-8d9e-25fb53b27e43"
          },
          {
            "name": "AA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    FILTER(",
              "        NOI_MONTHLY,",
              "        YEAR(NOI_MONTHLY[Post Month]) = 2024",
              "    ),",
              "    NOI_MONTHLY[Actual Amount]",
              ")"
            ],
            "lineageTag": "e56cb76d-d9f1-4513-aecb-67697c519ede"
          },
          {
            "name": "AA2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    FILTER(",
              "        NOI_MONTHLY,",
              "        YEAR(NOI_MONTHLY[Post Month]) = 2023",
              "    ),",
              "    NOI_MONTHLY[Actual Amount]",
              ")"
            ],
            "lineageTag": "7fb9a94b-ed02-441d-877b-6b9d1a8722f2"
          },
          {
            "name": "MaintenanceOpenCount",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(",
              "        MAINTENANCE_REQUEST_DAILY",
              "    ),",
              "    MAINTENANCE_REQUEST_DAILY[Maintenance Status Type] = \"Open\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "268b64b8-9823-46b1-886f-88abfc03c651"
          },
          {
            "name": "DaysToClose",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(MAINTENANCE_REQUEST_DAILY[Hours To Close])/24"
            ],
            "lineageTag": "f4129f0f-7233-41fd-aee7-c4fc7a918439"
          },
          {
            "name": "%Change-AMD",
            "expression": [
              "",
              "VAR FilteredData = ",
              "FILTER(",
              "    UNIT_SPACE_RENT_GROWTH_DAILY,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] <> 0 &&",
              "    NOT ISBLANK(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent]",
              "    ) &&",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent] <> 0 && ",
              "    NOT ISBLANK(UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent])",
              ")",
              "VAR Numerator =",
              "SUMX(",
              "    FilteredData,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] - UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "VAR Denominator =",
              "SUMX(",
              "    FilteredData,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "RETURN",
              "IF(",
              "    Denominator = 0 ,",
              "    0,",
              "    Numerator/Denominator",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7feec523-af15-41c8-b252-c9d201b4bada"
          },
          {
            "name": "RenewalRatio",
            "expression": [
              "",
              "VAR TotalExpirationCount =",
              "SUM(",
              "    LEASE_EXPIRATION_DAILY[Expiration Count]",
              ")",
              "VAR TotalRenewalCount =",
              "SUM(",
              "    LEASE_EXPIRATION_DAILY[Renewal Count]",
              ")",
              "RETURN",
              "IF(",
              "    TotalExpirationCount=0,",
              "    0,",
              "    TotalRenewalCount/TotalExpirationCount",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0911748-ae70-4f62-b16d-7b899ba0e79f"
          },
          {
            "name": "ChargeRecoveryRate",
            "expression": [
              "",
              "VAR TotalCurrentCharges =",
              "SUM(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges]",
              ")",
              "VAR TotalCurrentReceipts =",
              "SUM(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts]",
              ")",
              "VAR TotalPriorReceipts =",
              "SUM(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts]",
              ")",
              "VAR TotalCreditConcessions =",
              "SUM(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Credit Concessions]",
              ")",
              "RETURN",
              "IF(",
              "    TotalCurrentCharges = 0,",
              "    0,",
              "    DIVIDE(",
              "        (TotalCurrentReceipts + TotalPriorReceipts + TotalCreditConcessions),",
              "        TotalCurrentCharges",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0ba5db70-b4ca-4a7b-97db-a71cce8481b9"
          },
          {
            "name": "NetChargeAmount",
            "expression": [
              "",
              "SUMX(",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY,",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Charges] -",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Current Receipts] +",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Prior Receipts] + ",
              "    TRANSACTION_CHARGES_COLLECTIONS_MONTHLY[Credit Concessions]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3b7751d3-db36-4d99-8ca0-a767616b00a9"
          },
          {
            "name": "DistinctPropertyCount",
            "expression": [
              "",
              "COUNTROWS(",
              "    VALUES(",
              "        UNIT_OCCUPANCY_DAILY[Property ID]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c822c11c-69d1-45e2-afd8-c305e1771446"
          },
          {
            "name": "Leased%",
            "expression": [
              "",
              "IF(",
              "    SUM(",
              "        UNIT_OCCUPANCY_DAILY[Rentable Unit Count]) = 0,",
              "        0,",
              "        SUM(",
              "            UNIT_OCCUPANCY_DAILY[Rentable Leased Unit Count]",
              "        )/ ",
              "        SUM(UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              "        )",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6a9fdb6f-aa37-4317-a95a-1c193774f192"
          },
          {
            "name": "Exposed%",
            "expression": [
              "",
              "IF(",
              "    SUM(",
              "        UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              "    ) = 0,",
              "    0,",
              "    SUM(",
              "        UNIT_OCCUPANCY_DAILY[Rentable Exposed Unit Count]",
              "    )/",
              "    SUM(",
              "        UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fbf9f9ef-4066-4b9f-84ba-1adb4b6b8ef6"
          },
          {
            "name": "Available_Units",
            "expression": [
              "",
              "IF(",
              "    SELECTEDVALUE(",
              "        UNIT_OCCUPANCY_DAILY[Unit Status]",
              "    )",
              "    IN",
              "    {",
              "        \"Notice Unrented\", \"Vacant Unrented Ready\", \"Vacant Unrented Not Ready\"",
              "        },",
              "        1,",
              "        0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8a45d07c-5bc0-4622-b866-f8d285e5eb22"
          },
          {
            "name": "Loss_dueTo_Vacancy",
            "expression": [
              "",
              "IF(",
              "    SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Rentable Vacant Unit Count]) = 1 &&",
              "    SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Unit Status]) IN {\"Vacant Unrented Ready\", \"Vacant Unrented Not Ready\", \"Vacant Rented Ready\", \"Vacant Rented Not Ready\"} &&",
              "    SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Available On]) < TODAY(),",
              "    DATEDIFF(",
              "        TODAY(),",
              "        SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Available On]),",
              "        DAY",
              "    ) * (SELECTEDVALUE(UNIT_OCCUPANCY_DAILY[Market Rent]) / 30)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "82b9b308-cc25-4664-a75a-7d525e398eaf"
          },
          {
            "name": "Occupancy Monthly",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    AVERAGE(",
              "        UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              "    ) = 0,",
              "    0,",
              "    DIVIDE(",
              "        AVERAGE(",
              "            UNIT_OCCUPANCY_DAILY[Occupied Unit Count]",
              "        ),",
              "        AVERAGE(",
              "            UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              "        ),",
              "        0",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "05274163-a1a2-4e0a-bae7-ba1115c59e6d"
          },
          {
            "name": "Property ID (DistinctCount)",
            "expression": [
              "",
              "COUNTROWS(",
              "    VALUES(",
              "        UNIT_OCCUPANCY_DAILY[Property ID]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7189df3d-33f7-419b-b99c-670b8f47b909"
          },
          {
            "name": "NOI Budget YTD",
            "expression": [
              "",
              " CALCULATE(",
              "    SUM(NOI_MONTHLY[Budgeted Amount]),",
              "    YEAR(NOI_MONTHLY[Post Month])=YEAR(TODAY()) && NOI_MONTHLY[Post Month]<TODAY()",
              "    )"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "53d0e880-ffb1-473a-a27f-86e6931823bd"
          }
        ],
        "partitions": [
          {
            "name": "Measure Asset Management",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NOI_MONTHLY",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb7d07fc-d07c-41c7-bfd9-e7e109fef39c",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c23c4b84-e836-4883-891e-36bb01bb1495",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "122fdd19-0835-496e-ac38-9f755fc385bb",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c8ab078-fd16-4ef5-93c8-11e5ef971053",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b949505-4424-4101-9244-32fcd853aef3",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68156e09-92e4-4863-bb91-e3d1c31c4c0d",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40d744c4-808f-4024-8374-83a5be156038",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c6750c2-5cdf-4df3-94dc-9c66ce7e9cca",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d03254c-2001-43c9-b96c-af96e1317320",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "708d242b-6af9-4e89-97db-606ef9e72b57",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "GL Tree Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "730db9ae-16a8-4c06-829f-41992ee1e843",
            "sourceColumn": "GL Tree Name",
            "summarizeBy": "none"
          },
          {
            "name": "GL Book Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c564775d-f1b5-4061-863b-6165a7250c38",
            "sourceColumn": "GL Book Name",
            "summarizeBy": "none"
          },
          {
            "name": "GL Group ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b90b4f05-ab51-4365-83f0-607921d0bc09",
            "sourceColumn": "GL Group ID",
            "summarizeBy": "none"
          },
          {
            "name": "GL Group Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9de86333-80ba-42e3-bb32-bf330b60da6a",
            "sourceColumn": "GL Group Name",
            "summarizeBy": "none"
          },
          {
            "name": "Parent GL Group ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f08bc2-ed96-4841-8fae-c02d395702be",
            "sourceColumn": "Parent GL Group ID",
            "summarizeBy": "none"
          },
          {
            "name": "GL Account Type Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1dd4e807-27c7-43b0-a866-6be501566e11",
            "sourceColumn": "GL Account Type Name",
            "summarizeBy": "none"
          },
          {
            "name": "NOI GL Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c10bf42-828a-4581-b4f5-fb51a7850d36",
            "sourceColumn": "NOI GL Group",
            "summarizeBy": "none"
          },
          {
            "name": "Budget ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55b9b9e3-2fbe-49ed-88db-2bc7f10f3ebc",
            "sourceColumn": "Budget ID",
            "summarizeBy": "none"
          },
          {
            "name": "Budget Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b684d55-2219-45da-89b9-55bed61049a1",
            "sourceColumn": "Budget Name",
            "summarizeBy": "none"
          },
          {
            "name": "GL Account ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ab065b8-1f17-475e-bcf5-a0f65eff28d3",
            "sourceColumn": "GL Account ID",
            "summarizeBy": "none"
          },
          {
            "name": "Formatted Account Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "457f82c3-1d70-4600-a8a6-f8f577c2e2fd",
            "sourceColumn": "Formatted Account Number",
            "summarizeBy": "none"
          },
          {
            "name": "GL Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cecb9ce-0efd-4eba-95e2-7ffb52f59e53",
            "sourceColumn": "GL Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Post Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ce14e825-a008-4889-a0ed-413915bced5c",
            "sourceColumn": "Post Month",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5b6fcb7d-624f-4c04-aeea-88d18fc6cb84",
            "sourceColumn": "Actual Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Budgeted Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed5dd4cc-16d6-4a1d-91b0-65cde804910f",
            "sourceColumn": "Budgeted Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "17eb090e-20a0-49a0-93c7-fbfef84bbf6c",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b3c80b00-9bfb-45a6-9133-78a7ed8a707d",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b2e8977c-af2d-435c-b753-637975c444f2",
        "partitions": [
          {
            "name": "NOI_MONTHLY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"){[Name=\"ENTRATA_BI\"]}[Data], \"SELECT DISTINCT *#(lf)FROM #(lf)ENTRATA_BI.DASHBOARD.NOI_MONTHLY\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MAINTENANCE_REQUEST_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fd5a7a2-a9cc-4b99-a0e8-5b3776673c0b",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6a4977f-e29e-4da5-bd77-cb0c2b2c5299",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f537ee00-e716-44bd-9fc9-8ffc3e863283",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84156762-8716-47e9-8d75-f065d1f4a03f",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0c35f40-33e3-47ab-bd8f-8c9a8c037b82",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3184edbe-65a0-480f-bb56-c7c60a4b5db7",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "251d22f1-d43e-4dc9-b058-6e8e2e911cad",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad425567-1415-42f4-a237-bd9e90c29a5f",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07cf736e-43fb-45d9-b8ae-e36c399bfab6",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67a1e904-3285-4ffb-93d5-6626de068a58",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Request ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d61072b-b83a-466b-8238-766817cb61b5",
            "sourceColumn": "Maintenance Request ID",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Request Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f1df9e6-eccc-4d87-92ad-84871c6fdcc3",
            "sourceColumn": "Maintenance Request Type",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Priority Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c59ef73-66d7-4b47-9793-e0d91ef10b27",
            "sourceColumn": "Maintenance Priority Type",
            "summarizeBy": "none"
          },
          {
            "name": "Maintenance Status Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6455f87-9909-4b6d-a4c9-53cfeeee2090",
            "sourceColumn": "Maintenance Status Type",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce2880ea-4a10-4988-b906-5e3a2fe9019b",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3930c11-fa9a-4122-90fb-12ecf711a937",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Reference ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89c0362d-4eca-4d95-bbab-fe0dcff49d06",
            "sourceColumn": "Reference ID",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "934f607a-ea5e-4c31-bcdd-e1bc5ac84ee1",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Created By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a496bc73-5164-4ad1-bdbe-ff09c9b7ac85",
            "sourceColumn": "Created By",
            "summarizeBy": "none"
          },
          {
            "name": "Closed By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79502d25-8ce3-4a94-ba92-cea6696d768a",
            "sourceColumn": "Closed By",
            "summarizeBy": "none"
          },
          {
            "name": "Problem Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34ca982-66c9-44cc-b8d2-f2eeb0fd663f",
            "sourceColumn": "Problem Location",
            "summarizeBy": "none"
          },
          {
            "name": "Origin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fc8b22d-240a-4627-bf2e-2502bb58c69e",
            "sourceColumn": "Origin",
            "summarizeBy": "none"
          },
          {
            "name": "Opened On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e34acd8e-4331-4db5-80ed-19f2c47deea9",
            "sourceColumn": "Opened On",
            "summarizeBy": "none"
          },
          {
            "name": "Completed On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "83dbdc1c-11ed-4db9-b579-7c0fb59ded82",
            "sourceColumn": "Completed On",
            "summarizeBy": "none"
          },
          {
            "name": "Hours To Close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e592f22b-0ef6-43e8-bbbd-84164545fa7b",
            "sourceColumn": "Hours To Close",
            "summarizeBy": "sum"
          },
          {
            "name": "Suspended Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67a9643c-6649-460a-ae29-afd133e938d1",
            "sourceColumn": "Suspended Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Completed Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0ee80107-2776-4a27-b955-7a40e3536e6b",
            "sourceColumn": "Completed Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Cancelled Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "83080a2b-d283-46e1-a42a-af2c7bee6a44",
            "sourceColumn": "Cancelled Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3b2a50a6-0075-4506-98a6-6731db16cdb8",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7688387e-ba24-475d-8c07-95480de76986",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "AgeingBucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 2,\"0-2 Days\",",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 5,\"3-5 Days\",",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 14,\"6-14 Days\",",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 30,\"15-30 Days\",",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 60,\"31-60 Days\",",
              "    DATEDIFF(TODAY(),MAINTENANCE_REQUEST_DAILY[Opened On],DAY)<= 90,\"61-90 Days\",",
              "    TRUE(),\"90+\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "495645cc-72e5-4312-98ab-7c7c98c627f1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "ea3babfe-861d-423c-bfdc-46c8a97755e5",
        "partitions": [
          {
            "name": "MAINTENANCE_REQUEST_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    MAINTENANCE_REQUEST_DAILY_View = DASHBOARD_Schema{[Name=\"MAINTENANCE_REQUEST_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    MAINTENANCE_REQUEST_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UNIT_SPACE_RENT_GROWTH_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42e19438-c7e2-4cbf-8dc2-b2d68ff225bb",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2b7ad69-8ccb-44aa-8ad5-bd1b39380d27",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0535552e-67f0-48ac-9228-f3a900634a93",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4aeed981-686f-40b5-90ba-00cfacd7e384",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea38f258-22a9-4828-a5be-4fe12988d792",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "724bb581-b3de-4fa0-8dd8-f28eea4eb9f8",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce3e6eab-8a93-4adc-b57f-03c6db2980d4",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47361193-806b-4f77-bdba-0dbb5d067025",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6ab76cc-6926-49da-b17f-3c21dd5fecbd",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a169c4a9-b7fa-4228-a06a-732ee63339e0",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Space ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec5c0fe7-596f-4474-868c-868b65080222",
            "sourceColumn": "Unit Space ID",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d07f31b6-08f5-4967-a482-fe1896598b88",
            "sourceColumn": "Unit Number",
            "summarizeBy": "none"
          },
          {
            "name": "Floor Plan",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b556bad-023d-4f03-aced-a0e3c9fbe8d4",
            "sourceColumn": "Floor Plan",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Interval ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd6ed576-212e-4e70-8a7b-b0cd94f23cdd",
            "sourceColumn": "Lease Interval ID",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease Interval ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c88c5c90-eb09-46c1-86b4-cd0576247199",
            "sourceColumn": "Prior Lease Interval ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Interval Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "996410bc-a858-41b5-85ec-755511ad2c6b",
            "sourceColumn": "Lease Interval Type",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "adebad5f-63c0-4df3-a287-c77e2141b634",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "38b09d39-5142-4140-987c-eaf9631b0df2",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "991179f6-93bd-4056-a6ad-8499ae3d0144",
            "sourceColumn": "Prior Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Rent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb387333-6a97-4983-ab82-d1a86a33bab1",
            "sourceColumn": "Effective Rent",
            "summarizeBy": "sum"
          },
          {
            "name": "Prior Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d464cd9-4420-40ef-8cad-4a9a6f5704be",
            "sourceColumn": "Prior Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03cd02e6-84ac-4b7d-808f-f942359e6b92",
            "sourceColumn": "Prior Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd063390-6f40-4105-a41d-c433c3bbc854",
            "sourceColumn": "Prior Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1db190b4-3ae1-4d48-859a-4d8b81c7fa03",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc809c0d-b89e-49c9-9e1f-1df895806a90",
            "sourceColumn": "Resident First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb766c1e-6bf9-40a0-9664-0c60d90a5e3f",
            "sourceColumn": "Resident Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5566faf5-5dbe-4be2-b621-564e65453080",
            "sourceColumn": "Prior Lease Term",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Term",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a904b8e-1116-4763-8c45-9442fe2c508e",
            "sourceColumn": "Lease Term",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fbcf40d-c585-47c4-b301-4742969a5815",
            "sourceColumn": "Prior Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa57f187-f380-4050-a1c7-4ea4a743e93a",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb60480d-0959-4a2d-924f-af81e75a0ac3",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Effective Rent Per Sqft",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e7cdf9a9-bb05-4f8c-b2dc-32ffb1edb2a9",
            "sourceColumn": "Prior Effective Rent Per Sqft",
            "summarizeBy": "sum"
          },
          {
            "name": "Effective Rent Per Sqft",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bf29aeb7-795e-43c9-9567-5132cd5d825b",
            "sourceColumn": "Effective Rent Per Sqft",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bf7dc1f3-9767-418c-8281-5c9e67cce139",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0049886d-21a0-40e2-9207-f32a09d0b6fd",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          },
          {
            "name": "%Change-AMD1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR FilteredData = ",
              "FILTER(",
              "    UNIT_SPACE_RENT_GROWTH_DAILY,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] <> 0 &&",
              "    NOT ISBLANK(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent]",
              "    ) &&",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent] <> 0 && ",
              "    NOT ISBLANK(UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent])",
              ")",
              "VAR Numerator =",
              "SUMX(",
              "    FilteredData,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] - UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "VAR Denominator =",
              "SUMX(",
              "    FilteredData,",
              "    UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              ")",
              "RETURN",
              "IF(",
              "    Denominator = 0 ,",
              "    0,",
              "    Numerator/Denominator",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "a51249eb-e726-43a6-86c8-ee74003be671",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "2f54d269-72b5-41ea-b2f6-19726134a2bb",
        "partitions": [
          {
            "name": "UNIT_SPACE_RENT_GROWTH_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    UNIT_SPACE_RENT_GROWTH_DAILY_View = DASHBOARD_Schema{[Name=\"UNIT_SPACE_RENT_GROWTH_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    UNIT_SPACE_RENT_GROWTH_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEASE_EXPIRATION_DAILY",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f21c312-8206-42a3-81e4-2d7549db2e77",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0d3524e-9ace-4495-a343-a19dd01b2cf0",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a71520f-7180-4b30-9fac-ea93144a5d54",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a05e78a-ba6c-4cf4-9699-b99da435243a",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4aca8d8e-756d-44da-a84a-65fa95d94476",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "632d01af-063a-4e86-a4d7-4216f2dc0d67",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b185fb1-e199-4049-8a89-297942f249c7",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ed09bdc-dd05-4f59-8284-76e806fdb515",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef20dc70-4efe-4e09-9af5-ba79bb045953",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e15aafc-3b2e-4b7f-b091-57ebaeaa7495",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lease ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c3171cb-86fe-41b7-9a8d-804f36272467",
            "sourceColumn": "Lease ID",
            "summarizeBy": "none"
          },
          {
            "name": "Move-out Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "827fbfda-3f13-4fa1-b776-4fc705be9ce7",
            "sourceColumn": "Move-out Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "61ae193f-bcee-4550-82f7-0e47e2d834d4",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Expiration Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "25da1b2a-e5f5-403d-83d0-e4d36a9f1946",
            "sourceColumn": "Lease Expiration Date",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b25a4e68-a22f-4699-8419-e2967e1f4a70",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Resident Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cde683e3-28ce-4aec-8bfd-930ea78bdf7a",
            "sourceColumn": "Resident Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f25ea46-9713-47f5-b962-2de79a99517a",
            "sourceColumn": "Lease Status",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d48d220b-dce9-43d7-b838-ab5a3af604ee",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "668c9563-ac83-4473-aac6-ddb95e0bfec5",
            "sourceColumn": "Lease End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Expiration Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "83d122b6-f0e2-4de4-b9f8-a1b3acbe9fe9",
            "sourceColumn": "Expiration Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Renewal Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ee0f126-d62c-44be-8f7d-70c870d8f937",
            "sourceColumn": "Renewal Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Move-out Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7282916e-b36e-4abe-9703-0d5e3fc5fe52",
            "sourceColumn": "Move-out Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Undecided Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eb437a13-59cf-484f-9954-2f07a410e033",
            "sourceColumn": "Undecided Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "243e7a69-671d-40fe-be81-41f2079240da",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c6fcb887-fff3-49f7-8aa6-027a51bb8f4e",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aa6949ca-6b4b-4adf-968f-04bfbfdbb9f0",
        "partitions": [
          {
            "name": "LEASE_EXPIRATION_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"){[Name=\"ENTRATA_BI\"]}[Data], \"SELECT DISTINCT *#(lf)FROM #(lf)ENTRATA_BI.DASHBOARD.LEASE_EXPIRATION_DAILY\", null, [EnableFolding=true])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure Property Performance",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date Difference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": [
              "",
              "COALESCE(",
              "    IF(",
              "        SELECTEDVALUE(MAINTENANCE_REQUEST_DAILY[Maintenance Status Type]) = \"Opened\",open))"
            ],
            "lineageTag": "dd6c7cd2-16ba-47e6-9f1d-fbe64cb8dbc5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "111bfbea-0229-4a2f-bbd9-ee4ed35976fb",
        "measures": [
          {
            "name": "Occupancy%",
            "expression": [
              "",
              "VAR SumRentableUnitCount =",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Rentable Unit Count]",
              ")",
              "",
              "var SumOccupiedUnitCount = ",
              "SUM(",
              "    UNIT_OCCUPANCY_DAILY[Occupied Unit Count]",
              ")",
              "",
              "RETURN",
              "IF(",
              "    SumRentableUnitCount=0,",
              "    0,",
              "    DIVIDE(",
              "        SumOccupiedUnitCount,",
              "        SumRentableUnitCount",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "10f2d27c-228b-49cc-8f44-3a2fdf92ecdf"
          },
          {
            "name": "Lease End<30",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    MONTH(",
              "        SELECTEDVALUE(LEASE_EXPIRATION_DAILY[Lease End Date]) = MONTH(TODAY())) &&",
              "        YEAR(",
              "            SELECTEDVALUE(LEASE_EXPIRATION_DAILY[Lease End Date]) = YEAR(TODAY())),",
              "            1,",
              "            0",
              ")"
            ],
            "lineageTag": "c6c017f0-51e1-4f78-aaa0-afe3a9d382ae"
          },
          {
            "name": "%Change",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    AVERAGE(",
              "        UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "    ) = 0,",
              "    0,",
              "    (",
              "        AVERAGEX(",
              "            UNIT_SPACE_RENT_GROWTH_DAILY,",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] - ",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "        ) / ",
              "        AVERAGE(UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent])",
              "    )",
              ")"
            ],
            "lineageTag": "31f57e87-914a-4372-a356-c2e5222a216f"
          },
          {
            "name": "%Change - Application",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    AVERAGEX(",
              "        FILTER(",
              "            UNIT_SPACE_RENT_GROWTH_DAILY,",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] IN",
              "            {\"Application\", \"Transfer\"}",
              "        ),",
              "        AVERAGE(UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent])",
              "    ) = 0,",
              "    0,",
              "    (",
              "        AVERAGEX(",
              "            FILTER(",
              "                UNIT_SPACE_RENT_GROWTH_DAILY,",
              "                UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] IN {\"Application\", \"Transfer\"}",
              "            ),",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] - UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "        ) / AVERAGEX(",
              "            FILTER(",
              "                UNIT_SPACE_RENT_GROWTH_DAILY,",
              "                UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] IN {\"Application\", \"Transfer\"}",
              "            ),",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "99dd883c-9279-4e64-a867-3ca5a148e07b"
          },
          {
            "name": "% Change - Renewal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    AVERAGEX(",
              "        FILTER(",
              "            UNIT_SPACE_RENT_GROWTH_DAILY,",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] = \"Renewal\"",
              "        ),",
              "        AVERAGE(UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent])",
              "    ) = 0,",
              "    0,",
              "    (",
              "        AVERAGEX(",
              "            FILTER(",
              "                UNIT_SPACE_RENT_GROWTH_DAILY,",
              "                UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] = \"Renewal\"",
              "            ),",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Effective Rent] - UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "        ) / AVERAGEX(",
              "            FILTER(",
              "                UNIT_SPACE_RENT_GROWTH_DAILY,",
              "                UNIT_SPACE_RENT_GROWTH_DAILY[Lease Interval Type] = \"Renewal\"",
              "            ),",
              "            UNIT_SPACE_RENT_GROWTH_DAILY[Prior Effective Rent]",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "757146ff-eb94-405b-b808-80cdd9689bb4"
          },
          {
            "name": "Prior 60 Days",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(",
              "        MAINTENANCE_REQUEST_DAILY",
              "    ),",
              "    MAINTENANCE_REQUEST_DAILY[Maintenance Status Type] = \"Open\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "feee251e-ddb4-49bd-bde3-c35c725d3941"
          },
          {
            "name": "AgeReceviableBalance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    PROPERTY_AGE_RECEIVABLES_MONTHLY,",
              "    SWITCH(",
              "        PROPERTY_AGE_RECEIVABLES_MONTHLY[AgeReceivable],",
              "        \"all\",PROPERTY_AGE_RECEIVABLES_MONTHLY[Unpaid],",
              "        \"0-30\",PROPERTY_AGE_RECEIVABLES_MONTHLY[Aged Receivables 0 to 30],",
              "        \"31-60\",PROPERTY_AGE_RECEIVABLES_MONTHLY[Aged Receivables 31 to 60],",
              "        \"61-90\",PROPERTY_AGE_RECEIVABLES_MONTHLY[Aged Receivables 61 to 90],",
              "        \"90+\",PROPERTY_AGE_RECEIVABLES_MONTHLY[Aged Receivables 90+],",
              "        BLANK()",
              "    )",
              ")",
              "        "
            ],
            "lineageTag": "62a71ff4-0781-4f9a-b243-62c6a3c6744f"
          },
          {
            "name": "Net Performed Move-ins1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUM(LEASE_PROGRESSION_DAILY[Performed Move-in Count]) - ",
              "SUM(LEASE_PROGRESSION_DAILY[Performed Move-out Count])"
            ],
            "lineageTag": "af210ffa-0f60-4cf3-ae5d-14e3c4215855"
          }
        ],
        "partitions": [
          {
            "name": "Measure Property Performance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LEAD_SOURCE_DAILY",
        "columns": [
          {
            "name": "Client ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bebbe22a-1251-4a91-8a92-17fa686b0737",
            "sourceColumn": "Client ID",
            "summarizeBy": "none"
          },
          {
            "name": "Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "299eb3a4-160c-4b06-8b1b-0b844efae9a3",
            "sourceColumn": "Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c21654c-6def-4374-b434-dd0c6c945c5d",
            "sourceColumn": "Property ID",
            "summarizeBy": "none"
          },
          {
            "name": "Property Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "683cadd0-5c39-41b1-9719-05499e9e5f43",
            "sourceColumn": "Property Name",
            "summarizeBy": "none"
          },
          {
            "name": "Property Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed3107f1-57cb-426e-8fbe-d29fc5db48c0",
            "sourceColumn": "Property Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d535ec1-bab0-4649-853d-8dd023c253ea",
            "sourceColumn": "Property Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Property State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f07980-a91b-4308-b17f-9ce324acc60b",
            "sourceColumn": "Property State",
            "summarizeBy": "none"
          },
          {
            "name": "Property City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33cf710e-46e8-4c35-a210-0ab7a45d5d03",
            "sourceColumn": "Property City",
            "summarizeBy": "none"
          },
          {
            "name": "Property Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c956c5b-5ff2-4fd0-bb62-909b7651f104",
            "sourceColumn": "Property Address",
            "summarizeBy": "none"
          },
          {
            "name": "Property Zipcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e43ff306-3711-4ae0-a53e-e581a9cb1f13",
            "sourceColumn": "Property Zipcode",
            "summarizeBy": "none"
          },
          {
            "name": "Lead ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9adeb699-8572-47c6-a42a-7c4f627c88d2",
            "sourceColumn": "Lead ID",
            "summarizeBy": "none"
          },
          {
            "name": "Event Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f98d1816-d9c2-454a-99d1-1c8fa1337cef",
            "sourceColumn": "Event Date",
            "summarizeBy": "none"
          },
          {
            "name": "Event Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7d763327-9232-4544-aad4-32a29003e3e2",
            "sourceColumn": "Event Time",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0f2c317-2395-4f95-b740-5a50391d5690",
            "sourceColumn": "Lead Source",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "63165050-5703-4952-abfb-ff00172ab1a4",
            "sourceColumn": "Lead Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Move In",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fbf77cf1-407f-4006-a158-00bb542bbe28",
            "sourceColumn": "Move In",
            "summarizeBy": "sum"
          },
          {
            "name": "Move-in Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0e643e88-e276-47ef-b7ed-21dc2997dd19",
            "sourceColumn": "Move-in Date",
            "summarizeBy": "none"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc29cb7c-c22e-493f-853b-54c1d0300872",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33ff68a8-4de0-41a8-9dd7-5c9813ccdaa3",
            "sourceColumn": "Customer First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d417c8-7dd7-413f-8f68-d66235903a2a",
            "sourceColumn": "Customer Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae6273e7-0eeb-40cc-9e71-1ac5aa96125b",
            "sourceColumn": "Lead Status",
            "summarizeBy": "none"
          },
          {
            "name": "Leasing Agent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69431e3b-85ce-432b-98be-363f090284ad",
            "sourceColumn": "Leasing Agent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Original Contact Method",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c764ab3b-0751-4667-ae8c-f0dcd03f1d45",
            "sourceColumn": "Original Contact Method",
            "summarizeBy": "none"
          },
          {
            "name": "Building Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b32a8c9d-5a82-4ef3-a484-e214d82e6a8e",
            "sourceColumn": "Building Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Application Started Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5f7f9a42-7ff8-4711-a310-e9dd2183248d",
            "sourceColumn": "Application Started Date",
            "summarizeBy": "none"
          },
          {
            "name": "First Visit/Tour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bc9d2c46-df48-43b1-b3a8-6da8d48969b5",
            "sourceColumn": "First Visit/Tour",
            "summarizeBy": "none"
          },
          {
            "name": "Application Completed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "65cdc0d2-827c-4ada-9df2-13b5c20246ad",
            "sourceColumn": "Application Completed Date",
            "summarizeBy": "none"
          },
          {
            "name": "Application Approved Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fbea05b0-bf3a-415a-9366-0d1390f4d728",
            "sourceColumn": "Application Approved Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "29381dea-df93-4c5f-a205-4b0d13dc8fc5",
            "sourceColumn": "Lease Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Completed Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ebc6ce76-2d2a-4b38-8528-b3d1f7c82c18",
            "sourceColumn": "Lease Completed Date",
            "summarizeBy": "none"
          },
          {
            "name": "Lease Approved Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c0139398-79fb-42b6-b1e1-9c873c41abe2",
            "sourceColumn": "Lease Approved Date",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Updated On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "52067b53-dd9c-4a68-981b-2168949dca10",
            "sourceColumn": "Audit Updated On",
            "summarizeBy": "none"
          },
          {
            "name": "Audit Inserted On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b1e1390a-cdd8-40d8-ab75-19760184439c",
            "sourceColumn": "Audit Inserted On",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f206c47f-480d-49ef-90a4-688c1c3534ef",
        "partitions": [
          {
            "name": "LEAD_SOURCE_DAILY",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Snowflake.Databases(\"jsb49008.us-east-1.snowflakecomputing.com\",\"COMPUTE_WH\"),",
                "    ENTRATA_BI_Database = Source{[Name=\"ENTRATA_BI\",Kind=\"Database\"]}[Data],",
                "    DASHBOARD_Schema = ENTRATA_BI_Database{[Name=\"DASHBOARD\",Kind=\"Schema\"]}[Data],",
                "    LEAD_SOURCE_DAILY_View = DASHBOARD_Schema{[Name=\"LEAD_SOURCE_DAILY\",Kind=\"View\"]}[Data]",
                "in",
                "    LEAD_SOURCE_DAILY_View"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}